//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarrierOption
    {
        public int Id { get; set; }
        public Nullable<bool> IsUp { get; set; }
        public Nullable<bool> IsIn { get; set; }
        public Nullable<double> barrier { get; set; }
        public int InstTypeId { get; set; }
    
        public virtual InstType InstType { get; set; }
    }
}
