//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstType
    {
        public InstType()
        {
            this.BarrierOptions = new HashSet<BarrierOption>();
            this.DigitalOptions = new HashSet<DigitalOption>();
            this.Instruments = new HashSet<Instrument>();
            this.LookBackOptions = new HashSet<LookBackOption>();
        }
    
        public int Id { get; set; }
        public string TypeName { get; set; }
        public string Underlying { get; set; }
    
        public virtual ICollection<BarrierOption> BarrierOptions { get; set; }
        public virtual ICollection<DigitalOption> DigitalOptions { get; set; }
        public virtual ICollection<Instrument> Instruments { get; set; }
        public virtual ICollection<LookBackOption> LookBackOptions { get; set; }
    }
}
