//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterestRate
    {
        public int Id { get; set; }
        public Nullable<double> Tenor { get; set; }
        public Nullable<double> Rate { get; set; }
    }
}
