//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio_Manager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Portfolio_ManagerEntities : DbContext
    {
        public Portfolio_ManagerEntities()
            : base("name=Portfolio_ManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BarrierOption> BarrierOptions { get; set; }
        public virtual DbSet<DigitalOption> DigitalOptions { get; set; }
        public virtual DbSet<Instrument> Instruments { get; set; }
        public virtual DbSet<InstType> InstTypes { get; set; }
        public virtual DbSet<InterestRate> InterestRates { get; set; }
        public virtual DbSet<LookBackOption> LookBackOptions { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<Trade> Trades { get; set; }
    }
}
