//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade
    {
        public int Id { get; set; }
        public Nullable<bool> IsBuy { get; set; }
        public double Quantity { get; set; }
        public Nullable<double> UnderlyingP { get; set; }
        public Nullable<double> MarketPrice { get; set; }
        public double Price { get; set; }
        public string Timestamp { get; set; }
        public double PL { get; set; }
        public Nullable<double> Delta { get; set; }
        public Nullable<double> Gamma { get; set; }
        public Nullable<double> Vega { get; set; }
        public Nullable<double> Theta { get; set; }
        public Nullable<double> Rho { get; set; }
        public int InstrumentId { get; set; }
    
        public virtual Instrument Instrument { get; set; }
    }
}
